# https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
_extends: .github
version-template: $MAJOR.$MINOR.$PATCH
tag-template: v$NEXT_PATCH_VERSION
name-template: v$NEXT_PATCH_VERSION
